### ISSUE TITLE
integer argument expected, got float

### ISSUE THREAD

**Issue by peejcodes** [clear-code-projects/Pygame-Cameras#2]
Tried to run this and got this error:

Traceback (most recent call last):
  File "/storage/emulated/0/python/Github/Pygame-Cameras/camera.py", line 206, in <module>
    camera_group.custom_draw(player)
  File "/storage/emulated/0/python/Github/Pygame-Cameras/camera.py", line 170, in custom_draw
    scaled_surf = pygame.transform.scale(self.internal_surf,self.internal_surface_size_vector * self.zoom_scale)
TypeError: integer argument expected, got float

I tried some print statements to check what could be a float but didn't see anything.

**Comment by LucasColas** [comment]
And what if you write `scaled_surf = pygame.transform.scale(self.internal_surf,int(self.internal_surface_size_vector * self.zoom_scale))` ?
